<fieldset id="boardgame-freeform-fieldset" class="rows">
    <legend>Podrobnosti deskové hry</legend>
    <ol id="publication-freeform-fields">
        <li>
            <label for="title">Název:</label>
            <input type="text" name="title" id="title" value="[% whole.value.other.title %]" />
        </li>
        <li>
            <label for="author">Autor:</label>
            <input type="text" name="author" id="author" value="[% whole.value.other.author %]" />
        </li>
        <li>
            <label for="publisher">Vydavatel:</label>
            <input type="text" name="publisher" id="publisher" value="[% whole.value.other.publisher %]" />
        </li>
        <li>
            <label for="year">Rok vydání:</label>
            <input type="text" name="year" id="year" value="[% whole.value.other.year %]" />
        </li>
        <li>
            <label for="players">Počet hráčů:</label>
            <input type="text" name="players" id="players" value="[% whole.value.other.players %]" />
        </li>
        <li>
            <label for="age">Věk:</label>
            <input type="text" name="age" id="age" value="[% whole.value.other.age %]" />
        </li>
        <li>
            <label for="part_edition">Díl / Edice:</label>
            <input type="text" name="part_edition" id="part_edition" value="[% whole.value.other.part_edition %]" />
        </li>
        <li>
            <label for="isbn">EAN / ISBN:</label>
            <input type="text" name="isbn" id="isbn" value="[% whole.value.other.isbn %]" />
        </li>
    </ol>
</fieldset>
