<fieldset id="musiccd-freeform-fieldset" class="rows">
    <legend>Podrobnosti hudebního CD</legend>
    <ol id="publication-freeform-fields">
        <li>
            <label for="title">Název:</label>
            <input type="text" name="title" id="title" value="[% whole.value.other.title %]" />
        </li>
        <li>
            <label for="performer">Interpret:</label>
            <input type="text" name="performer" id="performer" value="[% whole.value.other.performer %]" />
        </li>
        <li>
            <label for="author">Autor / Skladatel:</label>
            <input type="text" name="author" id="author" value="[% whole.value.other.author %]" />
        </li>
        <li>
            <label for="publisher">Vydavatel / Label:</label>
            <input type="text" name="publisher" id="publisher" value="[% whole.value.other.publisher %]" />
        </li>
        <li>
            <label for="published_place">Místo vydání:</label>
            <input type="text" name="published_place" id="published_place" value="[% whole.value.other.published_place %]" />
        </li>
        <li>
            <label for="year">Rok vydání:</label>
            <input type="text" name="year" id="year" value="[% whole.value.other.year %]" />
        </li>
        <li>
            <label for="part_edition">Díl / Edice:</label>
            <input type="text" name="part_edition" id="part_edition" value="[% whole.value.other.part_edition %]" />
        </li>
        <li>
            <label for="volume">Číslo:</label>
            <input type="text" name="volume" id="volume" value="[% whole.value.other.volume %]" />
        </li>
        <li>
            <label for="isbn">EAN / ISBN:</label>
            <input type="text" name="isbn" id="isbn" value="[% whole.value.other.isbn %]" />
        </li>
    </ol>
</fieldset>
